@echo off
echo Combining SceneX documentation files...
type SCENEX_ANIMATION_SYSTEM.md > SCENEX_FULL_DOCUMENTATION.md
type SCENEX_ANIMATION_PART8.md >> SCENEX_FULL_DOCUMENTATION.md
type SCENEX_ANIMATION_PART9.md >> SCENEX_FULL_DOCUMENTATION.md
type SCENEX_ANIMATION_PART10.md >> SCENEX_FULL_DOCUMENTATION.md
echo Documentation combined into SCENEX_FULL_DOCUMENTATION.md
