blender:
  addons_path: addons/
  path: C:\Program Files\Blender Foundation\Blender 4.2\blender.exe
general:
  debug: true
  log_level: info
integrations:
  blender_gpt:
    api_key: null
    blender_path: C:\Program Files\Blender Foundation\Blender 4.2\blender.exe
    blendergpt_path: C:\ZB_Share\Labs\src\CluadeMCP\genai-agent-3d\integrations\blendergpt
    enabled: true
    model: gpt-4
  blendergpt:
    path: C:\ZB_Share\Labs\src\CluadeMCP\genai-agent-3d\integrations\blendergpt
  hunyuan3d:
    path: C:\ZB_Share\Labs\src\CluadeMCP\genai-agent-3d\integrations\hunyuan3d
  hunyuan_3d:
    device: cuda:0
    enabled: true
    hunyuan_path: C:\ZB_Share\Labs\src\CluadeMCP\genai-agent-3d\integrations\hunyuan3d
    output_dir: output/hunyuan/
    supported_formats:
    - obj
    - glb
    - gltf
    - usdz
    use_gpu: true
  trellis:
    path: C:\ZB_Share\Labs\src\CluadeMCP\genai-agent-3d\integrations\trellis
llm:
  model: llama3
  prompt_templates:
    json_generation: '

      You are a JSON generation assistant. Generate only valid, well-formed JSON with
      no explanations.

      The JSON should be properly formatted and include closing brackets.

      Do not include markdown code blocks or any text outside the JSON.

      '
  provider: ollama
  type: local
memory:
  file_path: data/memory/
  storage_type: redis
  ttl: 3600
redis:
  db: 0
  host: localhost
  password: null
  pool_size: 10
  port: 6379
  separate_connections: true
  timeout: 30
  use_connection_pool: true
scene:
  default_camera:
    position:
    - 5
    - -5
    - 5
    rotation:
    - 0.955
    - 0
    - 0.785
  default_light:
    energy: 1.0
    position:
    - 0
    - 0
    - 10
    type: SUN
tools:
  blender_gpt:
    class: BlenderGPTTool
    config:
      api_key: null
      blender_path: C:\Program Files\Blender Foundation\Blender 4.2\blender.exe
      blendergpt_path: C:\path\to\BlenderGPT
      model: gpt-4
      output_dir: output/blendergpt/
    enabled: false
    module: genai_agent.tools.blender_gpt_tool
  blender_script:
    class: BlenderScriptTool
    config:
      blender_path: C:\Program Files\Blender Foundation\Blender 4.2\blender.exe
    module: genai_agent.tools.blender_script
  diagram_generator:
    class: DiagramGeneratorTool
    config:
      output_dir: output/diagrams/
    module: genai_agent.tools.diagram_generator
  hunyuan_3d:
    class: Hunyuan3DTool
    config:
      device: cuda:0
      hunyuan_path: C:\path\to\Hunyuan3D-2
      output_dir: output/hunyuan/
      supported_formats:
      - obj
      - glb
      - gltf
      - usdz
      use_gpu: true
    enabled: false
    module: genai_agent.tools.hunyuan_3d_tool
  model_generator:
    class: ModelGeneratorTool
    config:
      output_dir: output/models/
    module: genai_agent.tools.model_generator
  scene_generator:
    class: SceneGeneratorTool
    config: {}
    module: genai_agent.tools.scene_generator
    parameters:
      output_dir: output/scenes
  svg_processor:
    class: SVGProcessorTool
    config:
      output_dir: output/svg/
    module: genai_agent.tools.svg_processor
  trellis:
    class: TrellisTool
    config:
      api_key: null
      model: gpt-4
      output_dir: output/trellis/
      trellis_path: C:\path\to\TRELLIS
    enabled: false
    module: genai_agent.tools.trellis_tool
